### ISSUE TITLE
Webサイト構成案

### ISSUE THREAD

**Issue by sakurashiki** [sakurashiki/libido_soft#1]
@furunyan 以下の構成でいこうと思う。どう？

|URL | ページ内容 |
|:---|:---| 
| / | 企業ページ(今回は作らずリダイレクトさせる) | 
| /dameane/ | 商品ページトップ |
| /dameane/concept.html | コンセプト |
| /dameane/story.html | ストーリー |
| /dameane/character.html | キャラクター情報 |
| /dameane/product.html | 製品情報 |

**Comment by araseitou0127** [comment]
問題ないです

**Comment by furunyan** [comment]
ストーリーとかコンセプトのページは作りますか？？

**Comment by sakurashiki** [comment]
@furunyan 間に合いそう？

**Comment by asaduki** [comment]
ダウンロードページ等はなくても大丈夫でしょうか？

**Comment by furunyan** [comment]
![tagu](https://cloud.githubusercontent.com/assets/18234338/14228105/da3767d2-f946-11e5-91df-e68a85279f2b.JPG)

**Comment by FujisakiRei** [comment]
この段階では自分からは特になし

**Comment by asaduki** [comment]
OKヽ(´▽｀)/

**Comment by araseitou0127** [comment]
変更内容意義なし。

**Comment by furunyan** [comment]
おｋ

**Comment by furunyan** [comment]
テスト

**Comment by furunyan** [comment]
テスト２
