### ISSUE TITLE
リリースまでの残タスク

### ISSUE THREAD

**Issue by sakurashiki** [sakurashiki/libido_soft#4]
- [x] キャラクターページのコーディング
- [x] 姉貴に下書きが残ってるので消す → 勘違いでした
- [x] 選択したページがわかるように
- [x] 戻るボタンがきくようにする
- [x] フォローボタンのコーディング
- [x] icoファイルのプリコンパイル

**Comment by sakurashiki** [comment]
https://github.com/sakurashiki/libido_soft/commit/cac3dd75e03274f1d269b605f1b6e6eb725b0322
https://github.com/sakurashiki/libido_soft/commit/ac8aa4b7d9bb7eea8a04157ef808bd16e1a4f3a8

**Comment by asaduki** [comment]
・【製品情報】木場さんの名前の横に　（Ｈシーン）　を追加
・【製品情報】ふじさきさんの名前を　ふじさき怜　に修正
・【キャラクター】八重樫鈴音の３サイズを　８８-６０-８８　に修正
