### ISSUE TITLE
リリースまでの修正点

### ISSUE THREAD

**Issue by sakurashiki** [sakurashiki/libido_soft#5]
#4 の続き

**Comment by asaduki** [comment]
・【製品情報】木場さんの名前の横に　（Ｈシーン）　を追加
・【製品情報】ふじさきさんの名前を　ふじさき怜　に修正
・【キャラクター】八重樫鈴音の３サイズを　８８-６０-８８　に修正

**Comment by asaduki** [comment]
・【キャラクター】キャラクターのセリフをわかりやすく表示

**Comment by asaduki** [comment]
・【ウィジェット】Twitterメインで情報発信するのであれば、『更新情報』と『リアルタイムのタイムライン』を別ツリーで確認出来るほうが見やすいと思う。

**Comment by sakurashiki** [comment]
- [ ] キャラクタ説明周り、alt属性の指定漏れを修正

**Comment by asaduki** [comment]
らじゃ。とりあえず問題は特になし。あとで発見したら、後日修正で対応しましょう。
